[project]
name = "fishboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "scikit-learn>=1.5.2",
    "streamlit>=1.40.2",
]

[dependency-groups]
dev = [
    "watchdog>=6.0.0",
]
